# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WinningNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalNums', models.CharField(max_length=255)),
                ('specialNum', models.IntegerField(blank=True, null=True)),
                ('lotteryType', models.CharField(max_length=50)),
                ('drawNo', models.CharField(max_length=50)),
                ('drawDate', models.DateField()),
            ],
            options={
                'ordering': ['drawNo', 'id'],
            },
        ),
    ]
