# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20180224_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winningnumbers',
            options={'ordering': ['-drawDate', '-drawNo', 'id']},
        ),
    ]
