# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineBot', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order_num', models.IntegerField()),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineBot.LineUser')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
    ]
